### ISSUE TITLE
and operator

### ISSUE THREAD

**Issue by tomfun** [twigjs/twig.js#235]
Maybe i just use old version, but and operator has a some strange behavior when i try do something like this
{% if "string" and ("exp" != "ression") %}
http://joxi.ru/V2VGpP5HzxbGAv

**Comment by evgenius** [comment]
@tomfun Would you mind renaming your temp variable and recreating the screenshot? I think you know why ;)

**Comment by evgenius** [comment]
Confirmed a serious issue with binary operators.
```twig
{% if app.user.id and (advert.owner.id != app.user.id) %}1{% else %}0{% endif %}
```
outputs `0` while it should be `1`.
```js
var context = {
	app: {
		user: {
			id: '123456'
		}
	},
	advert: {
		owner: {
			id: '654321'
		}
	}
};
```

**Comment by evgenius** [comment]
@justjohn 
A shorter example:
```twig
{% set app = { id: 1 } %}
{{ app.id and (app.id) }}
```
returns `false` (renders to an empty string).

It happens because of how RPN works.
In this case the stack looks like the following:
```
variable "app"
key "id"
param_start
variable "app"
key "id"
param_end
binary "and"
```
So in the infix notation it's the same as `app.id(app.id) and undefined` instead of the initial expression.
(Note: `undefined` appears because when `and` retrieves its two operands from the stack, it contains only one value.)

Do you think you can fix it? I can't figure out a quick fix. The issue seems serious to me.
We could mark the start token as "expression" somehow (the same way you mark the end token) but we need to make sure the binary operation token is located immediately before the start token.

Unfortunately it needs much more time than I have right now.

**Comment by tomfun** [comment]
I'll try to fix this, but not sure I have time for it.
more simple example:
```
"{{ app.id and true }}"
must:"1" not the empty string
```
- this work well
```
"{{ app.id and (true) }}"
must:"1" not the empty string
```
 -issue
trace:
http://joxi.ru/Q2Kj4PeFY97amj
http://joxi.ru/4AkZQKzSdMJd2q
