### ISSUE TITLE
Troubles while including template that uses extends in loops

### ISSUE THREAD

**Issue by bbeaulant** [twigjs/twig.js#436]
Hi,

I've got some troubles when using include in for loops. The included files do not "view" the overrided {% block %}.

I mention that I'm using precompiled templates.
Is it a bug or am I wrong ?

Exemple : 

File **A.twig**
```
{% block myBlock %}Hello A{% endblock %}
```

File **B.twig**
```
{% extends 'A.twig' %}
{% block myBlock %}Hello B{{ i }}{% endblock %}
```

File **Loop.twig**
```
{% for i in [1, 2, 3] %}
    {% include 'B.twig' %}
{% endfor %}
{% include 'B.twig' with { 'i':4 } %}
```

Renders :
```
Hello A
Hello A
Hello A
Hello B4
```

**Comment by lo-cwb** [comment]
+1 same issue on my project, did you find a fix or hack to by-pass the bug ?

Thx

**Comment by pterotech** [comment]
I also just encountered this problem. I thought I was screwing something up for the longest time

**Comment by pterotech** [comment]
Okay, so in twig.logic.js:
"Block Logic Tokens"

In parse, it says don't override previous blocks unless they're imported with "use", and loops should be exempted as well (comments on lines 6052 and 6053 of the full webpack compiled twig.js file)

So on line 6054, "context.loop" checked whether or not it is a loop. Deleting this fixes the functionality we are searching for.

But my question is -- what unintended side effects will this have? Is Twig for PHP not intended to have loops around included extended files (I haven't checked)? Is this going to cause unforeseen problems with loops within extended files or something?

![image](https://cloud.githubusercontent.com/assets/5229642/22771418/43d1989c-ee5c-11e6-8164-cfd987d34058.png)

**Comment by pterotech** [comment]
Okay so it seems when the for loop is called in the parent file, context.loop is set to true for when you enter the included child file... the intended effect is that if you have a block *within* a for loop it will overwrite the block output when you get to the next iteration, e.g.

    {% for i in [1, 2, 3] %}
        {% block loop_item %}{{ i }}{% endblock %}
    {% endfor %}

If you got rid of the context.loop, it will only write `1 1 1`

But as it stands, the context.loop being set to true by the initial outside-file for-loop causes any blocks to pass the check of context.loop, which causes it to always print the parent loop, since it thinks the block is already set they just have to grab the block which it already has...

**Comment by pbowden91** [comment]
I attempted to delve into the context structure but realized I wasn't strong enough in Twig to know the necessities of what changing things would do -- i.e. if I had a parent -> child1 -> child2 -> use multiple files / for loops within those files or includes or whatever, how things would propagate context-wise (at least throughout the Javascript file).

The problem lies in an included file's context knowing it is in a loop. 

From `twig.core.js`

	    Twig.ChildContext = function(context) {
	        var ChildContext = function ChildContext() {};
	        ChildContext.prototype = context;
	        return new ChildContext();
	    };

Which is called in the include/extend/for block logic tokens in `twig.logic.js`

A workaround for now is not including a context to the child, which can be done by using **with...only**. For example, in your code above:

File **Loop.twig**

    {% for i in [1, 2, 3] %}
        {% include 'B.twig' with { 'i': i } only %}
    {% endfor %}
    {% include 'B.twig' with { 'i':4 } %}

Renders
    Hello B1
    Hello B2
    Hello B3
    Hello B4


This fix is simple enough for me and works in my case. I hope it works in others' as well... I know it's silly writing it out like that but the child currently needs a local context to work with. If you want to bother with editing the actual library you can check out the Include block logic tokens for include and possibly expanding upon the ChildContext to let it know if it's the parent looping,..

**Comment by ericmorand-emakina** [comment]
This is definitely supposed to work:

https://twigfiddle.com/4jha45

Something is broken with twig.js support for blocks.

**Comment by ericmorand** [comment]
This is definitely supposed to work:



https://twigfiddle.com/4jha45



Something is broken with twig.js support for blocks.
