### ISSUE TITLE
update cdnjs's compiled twig.js

### ISSUE THREAD

**Issue by olets** [twigjs/twig.js#473]
0.8.9 (March 2016, justjohn/twig.js) is hosted on cdnjs: https://cdnjs.com/libraries/twig.js

This should be updated to the latest twigjs/twig.js. Anyone have experience with managing cdnjs?

**Comment by 7ochem** [comment]
cdnjs can be found on GitHub and twig.js is also in there: https://github.com/cdnjs/cdnjs/tree/master/ajax/libs/twig.js

There is a `package.json` containing information and instructions for cdnjs and this also includes an "autoupdate" section which cdnjs uses to auto update twig.js:

    "autoupdate": {
      "source": "git",
      "target": "git://github.com/justjohn/twig.js.git",
      "fileMap": [
        {
          "basePath": "",
          "files": [
            "twig.js",
            "twig.min.js",
            "twig.min.js.map"
          ]
        }
      ]
    },

Here are the docs on "autoupdate": https://github.com/cdnjs/cdnjs/blob/master/documents/autoupdate.md

However, since version 0.9 of twig.js, there are no `twig.js`, `twig.min.js` and `twig.min.js.map` files in the root of the source anymore. So this `package.json` in the cdnjs source should be updated. But to what, I don't know (yet)...

I just started searching for a JS client side Twig implementation today and found twig.js here. I always prefer to use a CDN for JS packages. But I don't know how cdnjs works (just found the cdnjs repo and files today when looking at how twig.js should be updated there).

**Comment by dmhendricks** [comment]
For those who don't mind using an alternative CDN:

https://cdn.jsdelivr.net/npm/twig/twig.min.js
https://unpkg.com/twig/twig.min.js
