### ISSUE TITLE
twig.js needs a cool icon

### ISSUE THREAD

**Issue by axten** [twigjs/twig.js#474]
twig js is very popular so in my option it needs an cool icon :)

something like:
https://github.com/bveldhuis/bolt-extension-twig-localization-filters/blob/master/icon.jpg
https://github.com/GawainLynch/bolt-extension-twig-extensions/blob/master/icon.png

please discuss!

**Comment by dave-irvine** [comment]
Yes I'd love one but I have no artistic talent whatsoever or budget to hire anyone.

**Comment by olets** [comment]
A while back I asked Fabien about using some variation of the `Twig` logo for `twig.js`. He said it would depend on the design "but I'm not sure this is a good idea as it could create confusion between the projects." Don't know exactly what he had in mind, but I do think it's important to not do anything that makes it look like `twig.js` is _endorsed_ by `Twig` (especially because it doesn't have feature parity).

But I agree, a cool logo would be cool!

**Comment by axten** [comment]
I agree, twig.js logo should differ from twig logo.
So maybe we should play with the [node logo](http://ecodile.com/wp-content/uploads/2015/10/node_icon2.png)...

maybe like this:
![twig logo](https://cloud.githubusercontent.com/assets/1412778/25371695/3b8752d2-2992-11e7-9104-73071380351b.png)

**Comment by dave-irvine** [comment]
I think the grass is too recognisably Twig (PHP), would be happy to go with just something text based.

**Comment by gsouf** [comment]
@axten  @dane-harnett I just did one http://svgur.com/i/1j0.svg

**Comment by olets** [comment]
A proposal that doesn't reuse anyone else's logo. Green and white are from Twig, yellow and charcoal design are from JS. Font is based on JS's

![twigjs-logo](https://user-images.githubusercontent.com/3282350/29336347-74f21bfa-81db-11e7-9583-c7e64723fbdd.png)

**Comment by dave-irvine** [comment]
@olets done

**Comment by olets** [comment]
🎉
