### ISSUE TITLE
twig.js shouldn't support the array's <.length> 

### ISSUE THREAD

**Issue by Kinghts** [twigjs/twig.js#592]
{{ array.length  }} in Twig render nothing, but twig.js got the array's length. 

this makes people confused, especially the FE-developers who use javascript more offen then PHP.

**Comment by ericmorand** [comment]
There is nothing that prevent that behaviour in Twig specs. It's even the opposite that is supported: any public property or method of an object represented by a variable is accessible in a template.

`length` is a public property of arrays in JavaScript and thus it is totally expected that it is accessible in the template.

It doesn't render nothing with TwigPHP because length is not a public property of arrays in PHP - arrays are not even objects to begin with.

FE developers should start by reading and understanding Twig specifications. Nothing can prevent them from accessing any public property or method of any object passed to the template.
