### ISSUE TITLE
Can we call a javascript functions inside of the twigJs template ?

### ISSUE THREAD

**Issue by moda20** [twigjs/twig.js#635]
I am referring to something like blade in Laravel, where I can just call any php function globally available inside  "{{ }}".  Is there anyway to add new globally available functions to the scope of the rendering ?

**Comment by toptalo** [comment]
Maybe this can help you somehow?
https://github.com/twigjs/twig.js/wiki/Extending-twig.js#functions

**Comment by ericmorand** [comment]
@moda20 if you don't want to add a custom function to twig.js, keep in mind that you can pass anything as data to your Twig template, which means you can pass functions as well as long as they are attributes of one of the object passed as data.

Consider the following template:

```twig
{{ data.callMeMaybe() }}
```

If you render this template with the following data:

```js
{
    data: {
        callMeMaybe: () => { return 'Please!!!'; }
    }
}
```

You'll obtain the following result:

```html
Please!!!
```

It works because `callMeMaybe` is an attribute of `data`. As such they are not considered as globals and thus are not expected to be part of twig.js known functions.

It works with a few caveats like this one:

https://github.com/twigjs/twig.js/issues/467

**Comment by willrowe** [comment]
To summarize, no it is not possible to include arbitrary JavaScript in a template like Laravel Blade. This project always seeks to be compatible with TwigPHP, so if it can't be done there, it usually can't be done here either.
