### ISSUE TITLE
{% use %} doesn't transfer {% set %} variables between templates after 1.14.0

### ISSUE THREAD

**Issue by Termonna** [twigjs/twig.js#693]
In version 1.13.3 i could transfer data between templates and render it:
data.twig:
```
{% set data = {foo: 'bar'} %}
```

index.twig:
```
{% use './data.twig' %}

<div>{{data.foo}}</div>
```

rendered index.html:
```
<div>bar</div>
```

In version 1.14.0 there are no errors but data in index.twig (and in index.html) is empty.

Downgrade to 1.13.3 fixed the problem in my project

**Comment by ericmorand** [comment]
Well, you are already lucky that it works with 1.13.3, because:

> The use tag only imports a template if it does not extend another template, if it does not define macros, and if the body is empty. But it can use other templates.

https://twig.symfony.com/doc/2.x/tags/use.html

It means that your `data.twig` template cannot be `use`d. Try your templates with twigfiddle, you'll se that they don't work.

From there, it is easy to understand why it is not possible to set data from a `use`d template.

**Comment by Termonna** [comment]
Hi @ericmorand!
Sorry for late response.

Here is an example of dummy project https://termonna.github.io/twigjsDummy/www/
I created in hastily so do not pay attention to file structure or anything else :)

Repo: https://github.com/Termonna/twigjsDummy/
index.twig https://github.com/Termonna/twigjsDummy/blob/master/src/index.twig
index-data.twig: https://github.com/Termonna/twigjsDummy/blob/master/src/index-data.twig

`npm run build` to build twig to html
`npm run dev` to setup localhost server on :8080 port.

You can try to install twigjs@latest and compare with twigjs@1.13.3

Thank you for reply!

**Comment by willrowe** [comment]
As mentioned, this is not supported by TwigPHP and is not supported by this project either, in order to be compatible. Here is an example of it not working [in TwigPHP](https://twigfiddle.com/83tlaj).

The main issue is that the `set` tag is used in the body of the template. As stated in [the docs for TwigPHP](https://twig.symfony.com/doc/2.x/tags/use.html#:~:text=The%20use%20tag%20only%20imports%20a%20template%20if%20it%20does%20not%20extend%20another%20template%2C%20if%20it%20does%20not%20define%20macros%2C%20and%20if%20the%20body%20is%20empty.%20But%20it%20can%20use%20other%20templates.), only templates with empty bodies are supported by `use`.
