### ISSUE TITLE
Chained functions passed as context object parameters not executed correctly

### ISSUE THREAD

**Issue by mgrsskls** [twigjs/twig.js#783]
Hi,

when chaining function calls passed as context object parameters, I get a wrong result.

I added a test for that in my fork: https://github.com/mgrsskls/twig.js/commit/86503fdfca7e87df636c1a58600361be4f233e4a You can see the expected result there. What I instead get is `-test2`.

I was trying to fix that (which worked), but that unfortunately broke a lot of other stuff… Could you maybe point me to where that would need to be fixed? I'd be happy to give it another try then!

Thanks!

**Comment by ericmorand** [comment]
Maybe I'm missing something but I don't get how it is supposed to work. `value()` returns a string and you then call `value2()` on that string. At the very least, I expect the output to be empty.

**Comment by ericmorand** [comment]
It works in Drupal because `attributes` in your example are instances of a special class provided by Drupal that provides chaining:

https://api.drupal.org/api/drupal/core%21lib%21Drupal%21Core%21Template%21Attribute.php/class/Attribute/8.2.x

So the issue is not coming from twigjs.

By the way, I created an emulation of Drupal attributes class some time ago, to use with JS flavors of Twig:

https://www.npmjs.com/package/drupal-attribute

Maybe it can help you. :)

**Comment by mgrsskls** [comment]
Oh, I didn't see your package yet. Cool, I will have a look into that, thanks!

Closing this :)
