### ISSUE TITLE
How to simply show the data in a template?

### ISSUE THREAD

**Issue by zachisit** [twigjs/twig.js#796]
I'm having a very difficult time understanding how to show my template with some data. It is throwing some sort of error, but while I _can_ catch the error I can't read what the error is stopping my twig logic to show.

```
// this is the data that I want to be passed into my shared template
let emailBodyData = { 'hi' : 'thank you for helping me kind reader' }

var template = Twig.twig({
            path: './templates/email/lorem.twig', // this is where my template lives
            rethrow: true,
        })
var el = template.render({ emailBodyData })

console.log(JSON.stringify(el))
```

Running this on a NodeJs app. Any help would be greatly appreciated.

**Comment by willrowe** [comment]
It looks like this issue is with this line:

```js
var el = template.render({ emailBodyData })
```

Unless there is an `emailBodyData` variable in the `templates/email/lorem.twig` template, it should not be wrapped like that, the data should be passed directly as the first parameter like:
```js
var el = template.render(emailBodyData)
```

If this does not solve the problem, please comment with the contents of the `templates/email/lorem.twig`.
