### ISSUE TITLE
Setting macros for a template

### ISSUE THREAD

**Issue by MichaelMackus** [twigjs/twig.js#807]
I couldn't find anywhere in the documentation on how to setup macros for a template. I used to be able to do this in an older version of twig.js:

```
        return twig({
            data: template
         }).render({
             value: value,
             data: data,
            macros: patientMacros()
         });
    
 
    // twig.js helper to construct macros template
    function patientMacros() {
        return twig({
            data: $('#patient-macros').html()
        }).render({}, {
            output: 'macros'
        });
   }
```

This doesn't appear to work anymore. I'm unsure how to get this working, everything I have tried just outputs "[object Object]" for the macro output. I'm assuming this is just a documentation issue.

**Comment by MichaelMackus** [comment]
I think there must be some issue with passing the macros like I'm doing above. Seems to be a BC break since this was working in previous versions of twig.js.

I did find you can pass the macro directly inside the template, and it does work this way:

```twig
Twig.twig({
            data: "{% macro test(param) %}macro{% endmacro %}{% import _self as macros %}test {{ macros.test() }}",
        }).render({
            value: value,
            data: data,
        });

**Comment by willrowe** [comment]
The `output` options were removed in [v1.14.0](https://github.com/twigjs/twig.js/releases/tag/1.14.0). There was discussion at the time about bumping to v2.0.0 because of the amount of changes and removal of some things like the `output` options, but unfortunately that never happened.

At the end of the day though, these were undocumented and for internal use only. Macros should only be defined inside templates for maximum compatibility with [Twig](https://github.com/twigphp/Twig).
