### ISSUE TITLE
Build HTML indentation

### ISSUE THREAD

**Issue by fadrnym** [twigjs/twig.js#868]
hi, I'm using twig for my projects (built on Parcel) and I'm having a problem with formatting after the build. Can you please advise me how to format the html correctly? Thanks a lot!

Example:

`</h1>

                                    <p class="category-title__description">
                        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas volutpat accumsan turpis. Phasellus cursus est ac arcu bibendum vehicula.
                    </p>
                            </div>
            </div>
</section>`

**Comment by RobLoach** [comment]
Good question! Have we implemented the [`spaceless` filter](https://twig.symfony.com/doc/2.x/filters/spaceless.html)?

**Comment by fadrnym** [comment]
No, unfortunately I don't need that. I thought if I use twig my HTML will break (indentation). I need repair only indentation. Thaks a lot!

**Comment by RobLoach** [comment]
Whitespace and indentation doesn't break HTML. You could pass it through an HTML prettifier or similar, or we could create a Twig.js extension to pass it through a prettifier too.

**Comment by willrowe** [comment]
The whitespace depends on how you format the template itself, but that is up to you and not something that Twig itself handles. Since this is a JavaScript implementation of [Twig](https://twig.symfony.com/) we attempt to match the PHP version as closely as possible. If you are seeing a difference in outputted whitespace from the PHP version, please open a new issue with an example of it working as expected on https://twigfiddle.com/ and what twig.js produces using [this template](https://codepen.io/pen?template=LYQawea).
